project:
  type: website

website:
  title: "Pyung Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: cv.pdf
        text: CV

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

