---
title: "About"
editor: visual
---

### Academic Positions

-   **Korea Social Science Data Archive at Seoul National University**
    -   Summer program for GIS and spatial statistics
    -   Teaching Assistant (Aug 2022)
-   **Korea Institute of Public Administration (KIPA)**
    -   National think-tank under the Prime Minister's Office
    -   Research Assistant (Jul 2020 - Dec 2020)

### Education

-   **Ph.D. in Public Policy and Political Economy**, 2021 - Current
    -   The University of Texas at Dallas (Expected graduation: Aug 2026)
    -   Brain Berry J.L. Scholar
-   **M.A. in Public Administration**, 2020
    -   Yonsei University
    -   Thesis: The Effect of Carbon Pricing -- Evidence from the Korean Emission Trading Scheme
    -   Committee: Hyonhoe Bae (Chair), Taejun Lah, Sounman Hong
-   **B.A. in Public Administration**, 2018
    -   Ajou University
    -   Graduate with *Summa Cum Laude*
    -   The Next Century Humanities Scholar
-   **Exchange Student**, Sept 2016 - Aug 2017
    -   Julius-Maximilians University of Wuerzburg, Germany

###### 

### Honors, Awards, and Scholarships

-   **Keith Lankford Taylor Fellowship**
    -   UT Dallas, 2023
-   **Brain Berry J.L. Scholarship**
    -   Funded by University of Texas at Dallas
    -   The highest honor of the doctoral program at the School of Economics, Political, and Policy Sciences
    -   Additional stipends (Aug 2021 -- Aug 2026, expected 5 years)
-   **UTD Graduate Studies Scholarship**
    -   Funded by University of Texas at Dallas
    -   Scholarship and stipends (Aug 2021 -- Aug 2026, expected 5 years)
-   **Brain Korea 21 PLUS Scholarship**
    -   Funded by National Research Foundation
    -   Nationally competitive scholarship supporting graduates
    -   Stipends (Mar 2018 -- Feb 2020, 2 years)
-   **YUPA Graduate Studies Scholarship**
    -   Funded by Yonsei University
    -   Scholarship (Mar 2018 -- Feb 2020, 2 yrs)
-   ***Summa Cum Laude***
    -   Ajou University, 2018
-   **The Next Century Humanities Scholarship**
    -   Funded by Korea Ministry of Education
    -   Nationally competitive scholarship supporting undergraduates in social sciences
    -   Scholarship and stipends (Mar 2015 -- Feb 2018, 3 years)
-   **Teaching Assistantship**
    -   Funded by Ajou University
    -   Stipends (Sept 2014 -- Aug 2016, 2 years)
-   **Excellence Award in Undergraduate Research Project**
    -   Ajou University, 2015
-   **Dean's list**
    -   Ajou University, 2015
-   **Merit-based Scholarship**
    -   Funded by Ajou University
    -   Scholarship (Sept 2014 -- Aug 2016, 1 semester)
-   **Dean's list**
    -   Ajou University, 2014

###### 

### Service

-   **Graduate Student Assembly** (Vice President)
    -   Department of Public Administration at Yonsei University
-   **Student Ambassadors**
    -   Office of Administration at Ajou University
