---
title: "Teaching"
editor: visual
---

### Instructor

-   **Advanced GIS and Spatial Statistics (graduate)**

    -   Korea Social Science Data Archive (Summer 2023)
    -   Rating: 9.84/10

-   **Introductory GIS and Spatial Statistics (graduate)**

    -   Korea Social Science Data Archive (Summer 2023)
    -   Rating: 9.54/10

###### 

### Teaching Assistant

1.  **Economics for Public Policy (graduate)**

    -   UT Dallas (Spring 2024)

2.  **Big Data Analysis and Machine Learning for Social Science (graduate)**

    -   Korea Social Science Data Archive (Winter 2024)

3.  **Descriptive and Inferential Statistics (graduate)**

    -   UT Dallas (Fall 2023)

4.  **Methods of Quantitative Analysis in the Social and Policy Sciences (graduate)**

    -   UT Dallas (Spring 2023; Fall 2022)

5.  **GIS and Spatial Statistics (graduate)**

    -   Korea Social Science Data Archive (Summer 2022)

6.  **American National Government (undergraduate)**

    -   UT Dallas (Spring 2022; Fall 2021)

7.  **Quantitative Policy Analysis (undergraduate)**

    -   Yonsei University (Fall 2019)

8.  **Forecasting Methods and Applications (graduate)**

    -   Yonsei University (Spring 2018)

9.  **Introduction to Korean Government (undergraduate)**

    -   Ajou University (Fall 2017)

10. **Research Methods in Public Administration (undergraduate)**

    -   Ajou University (Spring 2016)
